
variable "build_directory" {
  type    = string
  default = "../../builds"
}

variable "cpus" {
  type    = string
  default = "2"
}

variable "disk_size" {
  type    = string
  default = "40000"
}

variable "guest_additions_mode" {
  type    = string
  default = "attach"
}

variable "guest_additions_url" {
  type    = string
  default = ""
}

variable "headless" {
  type    = string
  default = "true"
}

variable "hyperv_switch" {
  type    = string
  default = "bento"
}

variable "iso_checksum" {
  type    = string
  default = "3022424f777b66a698047ba1c37812026b9714c5"
}

variable "iso_url" {
  type    = string
  default = "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
}

variable "memory" {
  type    = string
  default = "4096"
}

variable "template" {
  type    = string
  default = "windows-2019-standard"
}

variable "unattended_file_path" {
  type    = string
  default = "2019/Autounattend.xml"
}

variable "virtio_win_iso" {
  type    = string
  default = "~/virtio-win.iso"
}

locals {
  floppy_dir = "${path.root}/answer_files"
}

source "virtualbox-iso" "autogenerated_1" {
  communicator              = "winrm"
  cpus                      = "${var.cpus}"
  disk_size                 = "${var.disk_size}"
  floppy_files              = ["${local.floppy_dir}/${var.unattended_file_path}"]
  guest_additions_interface = "sata"
  guest_additions_mode      = "${var.guest_additions_mode}"
  guest_additions_path      = "C:/users/vagrant/VBoxGuestAdditions.iso"
  guest_additions_url       = "${var.guest_additions_url}"
  guest_os_type             = "Windows2016_64"
  hard_drive_interface      = "sata"
  headless                  = "${var.headless}"
  iso_checksum              = "${var.iso_checksum}"
  iso_interface             = "ide"
  iso_url                   = "${var.iso_url}"
  memory                    = "${var.memory}"
  output_directory          = "${var.build_directory}/packer-${var.template}-virtualbox"
  shutdown_command          = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout          = "15m"
  vboxmanage                = [["modifyvm", "{{ .Name }}", "--vram", "48"], ["modifyvm", "{{ .Name }}", "--audio", "none"]]
  winrm_password            = "vagrant"
  winrm_timeout             = "12h"
  winrm_username            = "vagrant"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "chef-solo" {
    cookbook_paths = ["${path.root}/cookbooks"]
    guest_os_type  = "windows"
    run_list       = ["packer::disable_uac", "packer::disable_restore", "packer::disable_windows_update", "packer::remove_defender", "packer::configure_power", "packer::disable_screensaver"]
  }

  provisioner "windows-restart" {
  }

  provisioner "chef-solo" {
    cookbook_paths = ["${path.root}/cookbooks"]
    guest_os_type  = "windows"
    run_list       = ["packer::vm_tools", "packer::features", "packer::enable_file_sharing", "packer::enable_remote_desktop", "packer::ui_tweaks"]
  }

  provisioner "windows-restart" {
  }

  provisioner "chef-solo" {
    cookbook_paths = ["${path.root}/cookbooks"]
    guest_os_type  = "windows"
    run_list       = ["packer::cleanup", "packer::defrag"]
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "${path.root}/scripts/cleanup.ps1"
  }
}
